logging:
  level.ch.luzlutz: error

app:
  strategyClass: ch.luzlutz.wallpaper.service.MacOsStrategy
  interval: 5000
  activeDownloadName: unsplash
  keepNewestFiles: 5
  downloads:
    - download:
      name: unsplash
      downloadClass: ch.luzlutz.service.rest.UnsplashImage
      endpoint: https://source.unsplash.com/random?
      targetDir: "~"
      prefix: _wallpaper_
    - download:
      name: flickr
      downloadClass: ch.luzlutz.service.rest.FlickrImage
      endpoint: https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=${secret.flickr.api_key}&user_id=${secret.flickr.user_id}%40N05&format=json&nojsoncallback=1&a=$a
      targetDir: "~"
      prefix: _wallpaper2_












